### ISSUE TITLE
experiment.stats() error

### ISSUE THREAD

**Issue by HarrietMuncey** [optimizely/optimizely-client-python#13]
My experiment instances do not have a stats() method so I cannot access the stats engine results

**Comment by HarrietMuncey** [comment]
Any update on this please?

**Comment by jgaul** [comment]
@HarrietMuncey -- apologies for the delay. The `stats()` method should be available on the `Experiment` object... if you uninstall the `optimizely` module, then reinstall it fresh, are you still unable to use the `stats()` method? If so, can you share a stack trace?

**Comment by HarrietMuncey** [comment]
@jgaul I have uninstalled and reinstalled several times but it doesn't fix it. Please see below:

AttributeError                            Traceback (most recent call last)
<ipython-input-73-2cc14a24e4e8> in <module>()
      1 import optimizely
      2 client = optimizely.Client(optimizely_api_token)
----> 3 client.Experiments.get(4883971194).stats()

AttributeError: 'Experiment' object has no attribute 'stats'

**Comment by jgaul** [comment]
@HarrietMuncey I double-checked this, and I'm confident this would work with the latest version of the library. perhaps you're installing the latest version to a different Python environment then the one you're actually running your code from. can you capture the `optimizely.__file__` for the imported `optimizely` module, then zip up the `optimizely

**Comment by HarrietMuncey** [comment]
[optimizely.zip](https://github.com/optimizely/optimizely-client-python/files/131133/optimizely.zip)

**Comment by jgaul** [comment]
thanks @HarrietMuncey! so i used the version of the library that you provided, which does look like the latest version, and i didn't have any issues... is there a chat client you use that i could chat with you live over?

**Comment by HarrietMuncey** [comment]
I just tried it again and it seems to work! Very bizarre.

**Comment by jgaul** [comment]
@HarrietMuncey -- ah, i'd guess somehow you were using an older/cached version of the lib. good to hear you're in business!

**Comment by HarrietMuncey** [comment]
Thanks for your help anyway!

**Comment by jgaul** [comment]
sure thing!
