### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by boydjj** [optimizely/optimizely-client-python#16]
I'd like to move our app over to Python 3, but this package is one of the blockers for us. Since we're heavy users I imagine I can spend some time to work on it, but without tests it might be tricky.

Can y'all provide some guidance re: supported Python versions? For our own use case and for compatibility reasons, I'd be happy to make sure it works on 2.7 and 3.4+.

Also, do you have any thoughts on contribution, tests, etc.? I notice `mock` is in `requirements.txt` but not referenced anywhere...

**Comment by ollamh** [comment]
+1

**Comment by mauerbac** [comment]
This has been addressed! Thanks @ollamh
