### ISSUE TITLE
Updating projects

### ISSUE THREAD

**Issue by wlowry88** [optimizely/optimizely-client-python#9]
Hi Developers!

I have been using the python client with pretty great success so far. However, it seems like I can't update and save groups.

An example:
after authenticating (I can see all the projects), Neither:

project = client.Projects.get(3163460041)
project.project_javascript = "alert('yo')"
project.save()
 
nor:
 
client.Projects.update(3163460041, {'project_name': "New Name"})
 
Neither will update.

There are no exceptions being thrown or any errors. I have been able to create projects with the python client and love the ease of it to keep things on the server.

Was hoping you might have an idea of how to help!
Best,
Will

**Comment by rwsmith** [comment]
Hi @wlowry88, I think the latest commit might have fixed your issue. Can you give it a try? Thanks!

**Comment by wlowry88** [comment]
@rwsmith Yes, @lucasoptimizely was great and fixed it!

Thanks!
